baseURL = "https://creohex.space/"
defaultContentLanguage = "en"
title = "My personal page"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "risotto"
enableGitInfo = false
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
googleAnalytics = ""
copyright = "© 2022 Creohex"

# temp:
relativeURLs = true

[author]
    name = "Creohex"

[[menu.main]]
    name = "home"
    weight = 10
    identifier = "home"
    url = "/"
# [[menu.main]]
#     name = "Posts"
#     weight = 20
#     identifier = "posts"
#     url = "/posts/"
[[menu.main]]
    name = "services"
    weight = 30
    identifier = "services"
    url = "/services/"

[params]
    # version = "4.x"
    # debug = false
    # since = "2022"
    # gitRepo = ""
    noindex = false

[params.theme]
    palette = "gruvbox-dark"
    mode = "dark-mode"

[params.about]
    title = ""
    description = ""
    logo = "/favicon.ico"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Creohex/"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:paradise.source@gmail.com"
